# Generated by Django 4.1.6 on 2023-02-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_createdby_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='createdby',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
